export const QUERY_KEYS = {
    DASHBOARD_TOTAL_PRODUCT_SOLD: "DASHBOARD_TOTAL_PRODUCT_SOLD",
    DASHBOARD_POINTS_GIVEN: "DASHBOARD_POINTS_GIVEN",
    DASHBOARD_POINTS_REDEEMED: "DASHBOARD_POINTS_REDEEMED",
    DASHBOARD_TOTAL_PRODUCTS: "DASHBOARD_TOTAL_PRODUCTS",
    COMPANY: "COMPANY"
}